---
# Benutzer-Einstellungen
dev_user: "jerome"
dev_home: "/home/{{ dev_user }}"

# Zsh Einstellungen
zsh_theme: "powerlevel10k/powerlevel10k"
zsh_plugins:
  - git
  - docker
  - kubectl
  - sudo

# Cloud Tools Versionen
go_version: "1.25.0"  # Hier die gewünschte Version eintragen
go_archive: "go{{ go_version }}.linux-amd64.tar.gz"
go_download_url: "https://go.dev/dl/{{ go_archive }}"

#terraform Einstellungen
terraform_version: "1.7.0"

# Docker Einstellungen
docker_users:
  - "{{ dev_user }}"

# System-Pakete, die für Neovim & NvChad benötigt werden
dependencies:
  - neovim
  - git
  - ripgrep
  - build-essential
  - unzip
  - python3-pip

# Pfade und Repository-Infos
nvim_dest_dir: "{{ ansible_env.HOME }}/.config/nvim"
nvchad_repo: "https://github.com/NvChad/starter"
backup_suffix: ".bak_{{ ansible_date_time.date }}"

# Vivaldi Einstellungen
vivaldi_package: "vivaldi-stable"
vivaldi_repo_url: "https://repo.vivaldi.com/archive/deb/"
vivaldi_gpg_key: "https://repo.vivaldi.com/archive/linux_signing_key.pub"