---
- name: Setup PC
  hosts: all
  become: yes
  roles:
    - zsh
    - nvchad
    - docker
    - kubernetes
    - vscode    
    - terraform 
    - keypassxc
    - obsidian
    - vivaldi
    - slack
    - postman
    - krita
    - spotify