---
- name: Setup PC
  hosts: localhost 
  connection: local
  become: yes
  roles:
    - zsh
    - nvchad
    - docker
    #- kubernetes
    #- vscode
    - nerdfont    
    - terraform 
    - keypassxc
    - obsidian
    - vivaldi
    - slack
    - postman
    - krita
    - spotify