---
- name: Install Zsh and Git
  ansible.builtin.apt:
    name:
      - zsh
      - git
    state: present
    update_cache: yes

- name: Change default shell to Zsh
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh

- name: Clone Oh My Zsh
  become: no
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1

- name: Clone Powerlevel10k Theme
  become: no
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Create .zshrc from template
  become: no
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    force: no
    remote_src: yes

- name: Set ZSH_THEME to powerlevel10k
  become: no
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'