---
- name: Add Krita PPA repository
  ansible.builtin.apt_repository:
    repo: "{{ krita_ppa }}"
    state: present
    update_cache: yes

- name: Install Krita
  ansible.builtin.apt:
    name: "{{ krita_package }}"
    state: present
    update_cache: yes

- name: Install Krita translation packages
  ansible.builtin.apt:
    name: krita-l10n
    state: present