---
- name: Add Krita PPA repository
  ansible.builtin.apt_repository:
    repo: 'ppa:krita-pim/ppa'
    state: present
    update_cache: yes

- name: Install Krita and support packages
  ansible.builtin.apt:
    name:
      - krita
      - krita-l10n  # Sprachpaket f√ºr Deutsch
    state: present